config/routes.rb
Rails.application.routes.draw do
  resources :payments
  resources :investments
  root 'calculations#index'
  post 'calculations/calculate_rates', as: 'calculate_rates'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/investment.rb
class Investment < ApplicationRecord
  validates :sum, presence: true, numericality: { greater_than: 0 }
  validates :period_in_months, presence: true, numericality: { greater_than: 0 }
  validates :rate, presence: true, numericality: { greater_than: 0, less_than: 1 }
  validates :time_months, presence: true, numericality: { greater_than: 0 }
  validates :delay_rate, presence: true, numericality: { greater_than: 0, less_than: 1 }

  default_scope { order(:id) }

  has_many :payments

  def expected_payed_rate
    (sum * rate / 12 * period_in_months).round(2)
  end

  def actually_payed_rate
    payments.sum do |payment|
      if ['normal', 'early_full'].include?(payment.amount_type)
        monthly_payment_rate
      else
        monthly_payment_rate_delay
      end
    end
  end

  def monthly_payment_debt
    (sum / period_in_months).round(2)
  end

  def monthly_payment_rate
    sum * rate / 12
  end

  def monthly_payment_total
    monthly_payment_debt + monthly_payment_rate
  end

  def monthly_payment_rate_delay
    sum * delay_rate / 12
  end

  def monthly_payment_total_delay
    monthly_payment_debt + monthly_payment_rate_delay
  end

  def early_full_payment
    sum - ((payments.count - 1) * monthly_payment_debt) + monthly_payment_rate
  end

  def early_full_payment_delay
    sum - (payments.count * monthly_payment_debt) + monthly_payment_rate_delay
  end  

  def actual_rate
    (actually_payed_rate / sum / period_in_months * 12).round(2)
  end
end

app/models/investments_calculator.rb
class InvestmentsCalculator
  def initialize(investments)
    @investments = investments
  end

  def expected_rate
    (@investments.sum(&:rate) / @investments.count()).round(2)
  end

  def actual_rate
    (@investments.sum(&:actual_rate) / @investments.count).round(2)
  end  
end

app/models/payment.rb
class Payment < ApplicationRecord
  validates :amount_type, presence: true
  default_scope { order(:id) }
  belongs_to :investment
  enum amount_type: { normal: 0, delayed: 1, early_full: 2, early_full_delay: 3 }

  def amount
    if amount_type == 'normal'
      sum = investment.monthly_payment_total
    elsif amount_type == 'delayed'
      sum = investment.monthly_payment_total_delay
    elsif amount_type == 'early_full'
      sum = investment.early_full_payment
    else
      sum = investment.early_full_payment_delay
    end

    sum.round(2)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/calculations_controller.rb
class CalculationsController < ApplicationController
  def index
  end

  def calculate_rates
    calculator = InvestmentsCalculator.new(Investment.all)
    @actual_rate = calculator.actual_rate
    @expected_rate = calculator.expected_rate
  end
end

app/controllers/investments_controller.rb
class InvestmentsController < ApplicationController
  before_action :set_investment, only: [:show, :edit, :update, :destroy]

  # GET /investments
  # GET /investments.json
  def index
    @investments = Investment.all
  end

  # GET /investments/1
  # GET /investments/1.json
  def show
  end

  # GET /investments/new
  def new
    @investment = Investment.new
  end

  # GET /investments/1/edit
  def edit
  end

  # POST /investments
  # POST /investments.json
  def create
    @investment = Investment.new(investment_params)

    respond_to do |format|
      if @investment.save
        format.html { redirect_to @investment, notice: 'Investment was successfully created.' }
        format.json { render :show, status: :created, location: @investment }
      else
        format.html { render :new }
        format.json { render json: @investment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /investments/1
  # PATCH/PUT /investments/1.json
  def update
    respond_to do |format|
      if @investment.update(investment_params)
        format.html { redirect_to @investment, notice: 'Investment was successfully updated.' }
        format.json { render :show, status: :ok, location: @investment }
      else
        format.html { render :edit }
        format.json { render json: @investment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /investments/1
  # DELETE /investments/1.json
  def destroy
    @investment.destroy
    respond_to do |format|
      format.html { redirect_to investments_url, notice: 'Investment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_investment
      @investment = Investment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def investment_params
      params.require(:investment).permit(:sum, :period_in_months, :rate, :time_months, :delay_rate)
    end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_payment, only: [:show, :edit, :update, :destroy]

  # GET /payments
  # GET /payments.json
  def index
    @payments = Payment.all
  end

  # GET /payments/1
  # GET /payments/1.json
  def show
  end

  # GET /payments/new
  def new
    @payment = Payment.new
  end

  # GET /payments/1/edit
  def edit
  end

  # POST /payments
  # POST /payments.json
  def create
    @payment = Payment.new(payment_params)

    respond_to do |format|
      if @payment.save
        format.html { redirect_to @payment, notice: 'Payment was successfully created.' }
        format.json { render :show, status: :created, location: @payment }
      else
        format.html { render :new }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payments/1
  # PATCH/PUT /payments/1.json
  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to @payment, notice: 'Payment was successfully updated.' }
        format.json { render :show, status: :ok, location: @payment }
      else
        format.html { render :edit }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1
  # DELETE /payments/1.json
  def destroy
    @payment.destroy
    respond_to do |format|
      format.html { redirect_to payments_url, notice: 'Payment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment
      @payment = Payment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def payment_params
      params.require(:payment).permit(:amount_type, :investment_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calculations_helper.rb
module CalculationsHelper
end

app/helpers/investments_helper.rb
module InvestmentsHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/calculations/calculate_rates.js.erb
$('#actual_rate').text('Actual rate: ' + '<%= @actual_rate %>');
$('#expected_rate').text('Expected rate: ' + '<%= @expected_rate %>');

app/views/calculations/index.html.erb
<h1>Calculations</h1>

<%= form_tag calculate_rates_path, remote: true do %>
  <%= label_tag 'sum', 'Investment sum:' %>
  <%= text_field_tag 'sum' %>

  <%= submit_tag 'Calculate'  %>
<% end %>

<%= label_tag 'actual_rate:', 'Actual rate:', id: 'actual_rate' %>
<%= label_tag 'expected_rate:', 'Expected rate:', id: 'expected_rate' %>

app/views/investments/_form.html.erb
<%= form_with(model: investment, local: true) do |form| %>
  <% if investment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(investment.errors.count, "error") %> prohibited this investment from being saved:</h2>

      <ul>
      <% investment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :sum %>
    <%= form.text_field :sum, id: :investment_sum %>
  </div>

  <div class="field">
    <%= form.label :period_in_months %>
    <%= form.number_field :period_in_months, id: :investment_period_in_months %>
  </div>

  <div class="field">
    <%= form.label :rate %>
    <%= form.text_field :rate, id: :investment_rate %>
  </div>

  <div class="field">
    <%= form.label :time_months %>
    <%= form.number_field :time_months, id: :investment_time_months %>
  </div>

  <div class="field">
    <%= form.label :delay_rate %>
    <%= form.text_field :delay_rate, id: :investment_delay_rate %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/investments/edit.html.erb
<h1>Editing Investment</h1>

<%= render 'form', investment: @investment %>

<%= link_to 'Show', @investment %> |
<%= link_to 'Back', investments_path %>

app/views/investments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Investments</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Sum</th>
      <th>Period in months</th>
      <th>Rate</th>
      <th>Time months</th>
      <th>Delay rate</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @investments.each do |investment| %>
      <tr>
        <td><%= investment.id %></td>
        <td><%= investment.sum %></td>
        <td><%= investment.period_in_months %></td>
        <td><%= investment.rate %></td>
        <td><%= investment.time_months %></td>
        <td><%= investment.delay_rate %></td>
        <td><%= link_to 'Show', investment %></td>
        <td><%= link_to 'Edit', edit_investment_path(investment) %></td>
        <td><%= link_to 'Destroy', investment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Investment', new_investment_path %>

app/views/investments/new.html.erb
<h1>New Investment</h1>

<%= render 'form', investment: @investment %>

<%= link_to 'Back', investments_path %>

app/views/investments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sum:</strong>
  <%= @investment.sum %>
</p>

<p>
  <strong>Period in months:</strong>
  <%= @investment.period_in_months %>
</p>

<p>
  <strong>Rate:</strong>
  <%= @investment.rate %>
</p>

<p>
  <strong>Time months:</strong>
  <%= @investment.time_months %>
</p>

<p>
  <strong>Delay rate:</strong>
  <%= @investment.delay_rate %>
</p>

<%= link_to 'Edit', edit_investment_path(@investment) %> |
<%= link_to 'Back', investments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Balancepl</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class='topnav'>
      <%= link_to 'Calculations', root_path, class: ('active' if current_page?(root_path)) %>
      <%= link_to 'Investments', investments_path, class: ('active' if current_page?(investments_path)) %>
      <%= link_to 'Payments', payments_path, class: ('active' if current_page?(payments_path)) %>
    </div>
    <div class='container'>
      <%= yield %>
    </div>
  </body>
</html>

app/views/payments/_form.html.erb
<%= form_with(model: payment, local: true) do |form| %>
  <% if payment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

      <ul>
      <% payment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :amount_type %>
    <%= form.select :amount_type, Payment.amount_types.keys.to_a %>
  </div>

  <div class="field">
    <%= form.label :investment_id %>
    <%= form.collection_select :investment_id, Investment.all, :id, :id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/payments/edit.html.erb
<h1>Editing Payment</h1>

<%= render 'form', payment: @payment %>

<%= link_to 'Show', @payment %> |
<%= link_to 'Back', payments_path %>

app/views/payments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Payments</h1>

<table>
  <thead>
    <tr>
      <th>Amount type</th>
      <th>Amount</th>
      <th>Investment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @payments.each do |payment| %>
      <tr>
        <td><%= payment.amount_type %></td>
        <td><%= payment.amount %></td>
        <td><%= payment.investment_id %></td>
        <td><%= link_to 'Show', payment %></td>
        <td><%= link_to 'Edit', edit_payment_path(payment) %></td>
        <td><%= link_to 'Destroy', payment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Payment', new_payment_path %>

app/views/payments/new.html.erb
<h1>New Payment</h1>

<%= render 'form', payment: @payment %>

<%= link_to 'Back', payments_path %>

app/views/payments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Amount:</strong>
  <%= @payment.amount %>
</p>

<p>
  <strong>Investment:</strong>
  <%= @payment.investment %>
</p>

<%= link_to 'Edit', edit_payment_path(@payment) %> |
<%= link_to 'Back', payments_path %>